# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: Install-Module Pester -Force -Scope CurrentUser
  displayName: Update Pester
  name: prepStep
  workingDirectory: $(build.sourcesDirectory)
  failOnStderr: 'true'
- powershell: Invoke-Pester
  displayName: Pester Tests
  name: firstStep
  workingDirectory: $(build.sourcesDirectory)
  failOnStderr: 'true'
  env:
    name: WightSci
- powershell: Test-ModuleManifest -Path .\EventLogConverter\EventLogConverter.psd1
  displayName: Test Module Manifest
  name: testModuleStep
  workingDirectory: $(build.sourcesDirectory)
  failOnStderr: 'true'
- powershell: Publish-Module -Path .\EventLogConverter -NuGetApiKey $(GALLERY_KEY)
  displayName: Publish to PowerShell Gallery
  name: publishStep
  workingDirectory: $(build.sourcesDirectory)
  failOnStderr: 'true'

